version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.1
    - 3.10.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
  - dependency-name: css-loader
    versions:
    - 5.2.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.15
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.4.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
